- name: upgrade Arch
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes 
- name: install common packages 
  become: yes
  package:
    name: "{{ item }}" 
    state: latest 
  with_items:
    - unzip
    - zip
    - the_silver_searcher
    - git       
    - curl
    - fish
    - feh
    - conky
