- name: install VIM 
  package: 
    name: vim
    state: latest
- name: install Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/home/vagrant/.vim/bundle/Vundle.vim"  


