- name: ensure there are no system rubies
  package:
    name: rubygems
    state: absent
- name: ensure there are no system rubies
  package:
    name: ruby
    state: absent
- name: install rvm gpg
  shell: "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"
  args:
- name: install rvm
  shell: "curl -sSL https://get.rvm.io | bash -s stable"
- name: install ruby
  shell: "/home/vagrant/.rvm/bin/rvm install 2.3"
- name: use ruby 
  shell: "/home/vagrant/.rvm/bin/rvm --default use 2.3"



